#!/bin/bash
# /etc/init.d/testdaemon
#
### BEGIN INIT INFO
# Provides: irrigation
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Irrigation server daemon process
# Description:    Runs up the irrigation server daemon process
### END INIT INFO

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    /usr/bin/python /usr/bin/irrigator.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    /usr/bin/python /usr/bin/irrigator.py stop
    ;;
  restart)
    echo "Restarting server"
    /usr/bin/python /usr/bin/irrigator.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/irrigator {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
